"""DNSH

Revision ID: 6cdd83b54ce4
Revises: 
Create Date: 2024-01-20 13:34:45.548028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdd83b54ce4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dnsh', sa.String(length=250)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_criteria', schema=None) as batch_op:
        batch_op.drop_column('dnsh')

    # ### end Alembic commands ###
