"""Add dnsh to ActivityCriteria

Revision ID: 867c4ad56af6
Revises: 6cdd83b54ce4
Create Date: 2024-01-21 09:45:02.157170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867c4ad56af6'
down_revision = '6cdd83b54ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_criteria', schema=None) as batch_op:
        batch_op.alter_column('dnsh',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_criteria', schema=None) as batch_op:
        batch_op.alter_column('dnsh',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
